# Ortak JPA ve Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Istanbul

# SLF4J / Logging Ayarları (Azure'da sorun çıkarabileceği için şimdilik konsola yönlendirelim)
logging.level.root=INFO
logging.level.com.jollifiy.gameanalytics=INFO

# EN ÖNEMLİ KISIM: Portu 8080'e sabitliyoruz
server.port=8080