spring.datasource.url=jdbc:postgresql://gameanalytics-db.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=postgresadmin
spring.datasource.password=GameAnalytics2026!
server.port=8080